meta_product_name: "Matcher"
meta_title: "Matcher - Matching at conferences, made easy."
meta_description: "Matcher helps investors to meet relevant startups – in no time"
meta_image: "cover.png" # should exist in `app/assets/images/`
